### ISSUE TITLE
What do you make in USD?

### ISSUE THREAD

**Issue by f00Dev** [AchoArnold/ama#17]
Hey AchoArnold,

What do you make in the industry, and do you feel that your salary commensurate's with your experience?

Thanks!

**Comment by AchoArnold** [comment]
Sorry for the late reply

**What do you make in the industry?**

I'm a freelancer so I do $30/hour

**Do you feel that your salary commensurate's with your experience?**

Nope i feel I'm under-compensated salary wise.
