### ISSUE TITLE
What is your opinion on Dart?

### ISSUE THREAD

**Issue by tenhobi** [AchoArnold/ama#19]
Dart can be used on web (compiled to JS via Dart2JS, [AngularDart](https://webdev.dartlang.org/angular/), ...), mobile ([Flutter](https://flutter.io/)), server etc.

Have you ever tried it, maybe as alternative to Javascript? (also, Sass now uses Dart) What is your opinion on this language and it's platform? :-)

**Comment by AchoArnold** [comment]
I've never tried Dart and I've never even looked into it. So not much I can give.
Sorry
